### ISSUE TITLE
[BUG] Initial world spawn at 0,0,0 with 1.3.0 in MC 1.17.1 with default settings

### ISSUE THREAD

**Issue by Danklor** [DaFuqs/GlobalSpawn#9]
Every time I generate a single player world in MC 1.17.1 with this mod (1.3.0) with default settings I was spawned at 0,0,0 and suffocate in bedrock.  After the initial death the respawn location is correct. There is no crash or other interesting info in the logs.

Since the default config has the initial spawn position disabled, I would not expect this to happen.  Even if it was enabled, the default location should be 50,80,50.

**Comment by DaFuqs** [comment]
Thank you for the report. I must have introduced that issue in 1.3.0 when I made the mod work in singleplayer, too.
I will fix it and will let you know. In the meantime if you only need that mod for multiplayer you can remove it in your singleplayer instance no problem, since it runs perfectly fine just being installed server side.
